import User from "../models/User";
import OrganizerProfile from "../models/OrganizerProfile";

export const seedUsers = async (): Promise<void> => {
  const baseUsers = [
    {
      firstName: "Paromita",
      lastName: "Porel",
      email: "paromitaporel41@gmail.com",
      password: "paromita123",
      phone: "+91 98765 43210",
      city: "Kolkata",
      role: "customer" as const,
      avatar: "PP",
    },
    {
      firstName: "Arjun",
      lastName: "Mehta",
      email: "arjun@mehtaevents.com",
      password: "arjun123",
      phone: "+91 99887 76655",
      city: "Mumbai",
      role: "organizer" as const,
      avatar: "AM",
      organizerProfile: {
        businessName: "Mehta Events & Celebrations",
        specialties: ["Wedding", "Corporate", "Destination Wedding"],
        city: "Mumbai",
        yearsOfExperience: "5-10 yrs",
        rating: 4.8,
        reviewCount: 214,
        totalBookings: 47,
        totalRevenue: 1840000,
        isVerified: true,
        isKYCSubmitted: true,
        isKYCApproved: true,
        commissionRate: 12,
      },
    },
    {
      firstName: "Naina",
      lastName: "Khanna",
      email: "naina@khannaweddings.in",
      password: "naina123A!",
      phone: "+91 98310 22334",
      city: "Delhi",
      role: "organizer" as const,
      avatar: "NK",
      organizerProfile: {
        businessName: "Khanna Weddings",
        specialties: ["Wedding", "Sangeet", "Luxury Decor"],
        city: "Delhi",
        yearsOfExperience: "10+ yrs",
        rating: 4.7,
        reviewCount: 148,
        totalBookings: 34,
        totalRevenue: 1425000,
        isVerified: true,
        isKYCSubmitted: true,
        isKYCApproved: true,
      },
    },
    {
      firstName: "Raghav",
      lastName: "Rao",
      email: "raghav@raoevents.com",
      password: "Raghav123!",
      phone: "+91 98450 11223",
      city: "Bengaluru",
      role: "organizer" as const,
      avatar: "RR",
      organizerProfile: {
        businessName: "Rao Events & Co.",
        specialties: ["Corporate", "Conference", "Launch Events"],
        city: "Bengaluru",
        yearsOfExperience: "3-5 yrs",
        rating: 4.6,
        reviewCount: 89,
        totalBookings: 26,
        totalRevenue: 920000,
        isVerified: true,
        isKYCSubmitted: true,
        isKYCApproved: true,
      },
    },
    {
      firstName: "Fatima",
      lastName: "Sheikh",
      email: "fatima@goavibes.in",
      password: "Fatima123!",
      phone: "+91 98900 33445",
      city: "Goa",
      role: "organizer" as const,
      avatar: "FS",
      organizerProfile: {
        businessName: "Goa Vibes Collective",
        specialties: ["Beach Party", "DJ Night", "Buffet Night"],
        city: "Goa",
        yearsOfExperience: "5-10 yrs",
        rating: 4.9,
        reviewCount: 176,
        totalBookings: 41,
        totalRevenue: 1670000,
        isVerified: true,
        isKYCSubmitted: true,
        isKYCApproved: true,
      },
    },
    {
      firstName: "Vikram",
      lastName: "Sisodia",
      email: "vikram@royaludaipur.com",
      password: "Vikram123!",
      phone: "+91 98290 55667",
      city: "Udaipur",
      role: "organizer" as const,
      avatar: "VS",
      organizerProfile: {
        businessName: "Royal Udaipur Experiences",
        specialties: ["Destination Wedding", "Cultural Show", "Heritage Event"],
        city: "Udaipur",
        yearsOfExperience: "10+ yrs",
        rating: 4.9,
        reviewCount: 203,
        totalBookings: 39,
        totalRevenue: 2590000,
        isVerified: true,
        isKYCSubmitted: true,
        isKYCApproved: true,
      },
    },
    {
      firstName: "Rahul",
      lastName: "Sharma",
      email: "rahul.sharma@example.com",
      password: "Rahul123!",
      phone: "+91 98111 22334",
      city: "Mumbai",
      role: "customer" as const,
      avatar: "RS",
    },
    {
      firstName: "Sonia",
      lastName: "Kapoor",
      email: "sonia.kapoor@example.com",
      password: "Sonia123!",
      phone: "+91 98111 33445",
      city: "Delhi",
      role: "customer" as const,
      avatar: "SK",
    },
    {
      firstName: "Amit",
      lastName: "Verma",
      email: "amit.verma@example.com",
      password: "Amit1234!",
      phone: "+91 98222 44556",
      city: "Pune",
      role: "customer" as const,
      avatar: "AV",
    },
    {
      firstName: "Priya",
      lastName: "Mani",
      email: "priya.mani@example.com",
      password: "Priya123!",
      phone: "+91 98333 55667",
      city: "Chennai",
      role: "customer" as const,
      avatar: "PM",
    },
    {
      firstName: "Anjali",
      lastName: "Shah",
      email: "anjali.shah@example.com",
      password: "Anjali123!",
      phone: "+91 98444 66778",
      city: "Ahmedabad",
      role: "customer" as const,
      avatar: "AS",
    },
    {
      firstName: "Karan",
      lastName: "Mehra",
      email: "karan.mehra@example.com",
      password: "Karan123!",
      phone: "+91 98555 77889",
      city: "Jaipur",
      role: "customer" as const,
      avatar: "KM",
    },
  ];

  for (const entry of baseUsers) {
    const user = await User.create({
      firstName: entry.firstName,
      lastName: entry.lastName,
      email: entry.email,
      password: entry.password,
      phone: entry.phone,
      city: entry.city,
      role: entry.role,
      avatar: entry.avatar,
      isEmailVerified: true,
      isActive: true,
      promos:
        entry.email === "paromitaporel41@gmail.com"
          ? [
              {
                code: "WELCOME10",
                discount: 10,
                expiresAt: new Date("2026-12-31"),
                used: false,
              },
            ]
          : [],
    });

    if ("organizerProfile" in entry) {
      await OrganizerProfile.create({
        user: user._id,
        ...entry.organizerProfile,
      });
    }
  }
};
