import OrganizerProfile from "../models/OrganizerProfile";
import User from "../models/User";
import Venue from "../models/Venue";

export const seedVenues = async (): Promise<void> => {
  const organizers = await User.find({ role: "organizer" }).lean();
  const organizerProfiles = await OrganizerProfile.find().lean();

  const userByEmail = new Map(organizers.map((organizer) => [organizer.email, organizer]));
  const profileByUserId = new Map(organizerProfiles.map((profile) => [String(profile.user), profile]));

  const venues = [
    {
      organizerEmail: "arjun@mehtaevents.com",
      name: "The Grand Mehta Banquet",
      description: "A luxurious banquet hall in Bandra with premium decor, seamless valet, and multi-cuisine catering.",
      city: "Mumbai",
      address: "Linking Road, Bandra West, Mumbai",
      coordinates: [72.8369, 19.0664],
      coverImage: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?q=80&w=2074&auto=format&fit=crop",
      images: [
        "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?q=80&w=2074&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?q=80&w=2070&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=2070&auto=format&fit=crop",
      ],
      capacity: 500,
      pricePerEvent: 120000,
      eventTypes: ["Wedding", "Reception", "Corporate Event"],
      amenities: ["WiFi", "Parking", "Catering", "AC", "Stage", "Projector", "Valet"],
      tags: ["premium", "indoor", "banquet"],
      rating: 4.9,
      reviewCount: 120,
      totalBookings: 45,
      totalRevenue: 5400000,
      status: "active" as const,
      isTopPick: true,
      isFeatured: true,
    },
    {
      organizerEmail: "arjun@mehtaevents.com",
      name: "Skyline Terrace",
      description: "An intimate rooftop venue with skyline views, mood lighting, and flexible event styling.",
      city: "Mumbai",
      address: "Powai Lake Road, Powai, Mumbai",
      coordinates: [72.9081, 19.1197],
      coverImage: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?q=80&w=2070&auto=format&fit=crop",
      images: [
        "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?q=80&w=2070&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?q=80&w=2070&auto=format&fit=crop",
      ],
      capacity: 150,
      pricePerEvent: 65000,
      eventTypes: ["Birthday", "Anniversary", "DJ Night"],
      amenities: ["WiFi", "Parking", "Catering", "Stage", "Valet"],
      tags: ["rooftop", "evening", "music"],
      rating: 4.7,
      reviewCount: 56,
      totalBookings: 32,
      totalRevenue: 2080000,
      status: "active" as const,
      isFeatured: true,
    },
    {
      organizerEmail: "arjun@mehtaevents.com",
      name: "Mehta Garden Villa",
      description: "A destination-style garden villa ideal for larger celebrations and premium outdoor experiences.",
      city: "Alibaug",
      address: "Varsoli, Alibaug, Maharashtra",
      coordinates: [72.8777, 18.6414],
      coverImage: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2070&auto=format&fit=crop",
      images: [
        "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2070&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=2070&auto=format&fit=crop",
      ],
      capacity: 800,
      pricePerEvent: 250000,
      eventTypes: ["Destination Wedding", "Large Celebration"],
      amenities: ["Parking", "Catering", "Stage", "Valet", "Green Room"],
      tags: ["outdoor", "destination", "villa"],
      rating: 4.8,
      reviewCount: 38,
      totalBookings: 12,
      totalRevenue: 3000000,
      status: "active" as const,
      isTopPick: true,
    },
    {
      organizerEmail: "naina@khannaweddings.in",
      name: "Regal Orchid Palace",
      description: "A grand palace-inspired Delhi venue with high ceilings, chandeliers, and luxe bridal suites.",
      city: "Delhi",
      address: "NH-8, Aerocity, New Delhi",
      coordinates: [77.1218, 28.5562],
      coverImage: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?q=80&w=2070&auto=format&fit=crop",
      images: [
        "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?q=80&w=2070&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1519225421980-715cb0215aed?q=80&w=2070&auto=format&fit=crop",
      ],
      capacity: 700,
      pricePerEvent: 180000,
      eventTypes: ["Wedding", "Sangeet", "Reception"],
      amenities: ["Parking", "Catering", "AC", "Stage", "Valet"],
      tags: ["luxury", "wedding", "indoor"],
      rating: 4.8,
      reviewCount: 102,
      totalBookings: 29,
      totalRevenue: 3480000,
      status: "active" as const,
      isFeatured: true,
    },
    {
      organizerEmail: "naina@khannaweddings.in",
      name: "Amber Courtyard Lawns",
      description: "Classic open lawns for sangeet nights, mehendi brunches, and elegant family functions.",
      city: "Delhi",
      address: "Chattarpur, New Delhi",
      coordinates: [77.1901, 28.4948],
      coverImage: "https://images.unsplash.com/photo-1469371670807-013ccf25f16a?q=80&w=2070&auto=format&fit=crop",
      images: [
        "https://images.unsplash.com/photo-1469371670807-013ccf25f16a?q=80&w=2070&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1505236858219-8359eb29e329?q=80&w=2070&auto=format&fit=crop",
      ],
      capacity: 350,
      pricePerEvent: 90000,
      eventTypes: ["Mehendi", "Engagement", "Brunch"],
      amenities: ["Parking", "Catering", "Stage"],
      tags: ["lawns", "outdoor", "family"],
      rating: 4.5,
      reviewCount: 68,
      totalBookings: 21,
      totalRevenue: 1890000,
      status: "active" as const,
    },
    {
      organizerEmail: "raghav@raoevents.com",
      name: "Tech Convention Center",
      description: "A modern conference center with breakout rooms, staging, and livestreaming-ready AV.",
      city: "Bengaluru",
      address: "Whitefield Main Road, Bengaluru",
      coordinates: [77.7499, 12.9698],
      coverImage: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?q=80&w=2070&auto=format&fit=crop",
      images: [
        "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?q=80&w=2070&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1475721027185-39a12947c004?q=80&w=2070&auto=format&fit=crop",
      ],
      capacity: 800,
      pricePerEvent: 150000,
      eventTypes: ["Corporate Event", "Conference", "Meeting"],
      amenities: ["WiFi", "Parking", "AC", "Stage", "Projector"],
      tags: ["conference", "corporate", "tech"],
      rating: 4.6,
      reviewCount: 95,
      totalBookings: 24,
      totalRevenue: 3600000,
      status: "active" as const,
    },
    {
      organizerEmail: "raghav@raoevents.com",
      name: "Cubix Launch Studio",
      description: "A slick studio-style venue built for product launches, talks, and branded experiences.",
      city: "Bengaluru",
      address: "Indiranagar, Bengaluru",
      coordinates: [77.6408, 12.9719],
      coverImage: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=2070&auto=format&fit=crop",
      images: [
        "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=2070&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=2070&auto=format&fit=crop",
      ],
      capacity: 220,
      pricePerEvent: 75000,
      eventTypes: ["Launch Event", "Panel Discussion", "Networking"],
      amenities: ["WiFi", "Parking", "Projector", "Stage"],
      tags: ["studio", "urban", "branding"],
      rating: 4.4,
      reviewCount: 41,
      totalBookings: 15,
      totalRevenue: 1125000,
      status: "under_review" as const,
    },
    {
      organizerEmail: "fatima@goavibes.in",
      name: "Beachside Cabana",
      description: "A vibrant beachfront venue with live bar setups, sunset decks, and barefoot party energy.",
      city: "Goa",
      address: "Calangute Beach, Goa",
      coordinates: [73.7639, 15.5439],
      coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=2070&auto=format&fit=crop",
      images: [
        "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=2070&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1520483601560-389dff434fdf?q=80&w=2070&auto=format&fit=crop",
      ],
      capacity: 150,
      pricePerEvent: 120000,
      eventTypes: ["Party", "Bachelor Party", "DJ Night"],
      amenities: ["Beachfront", "Bar", "Parking", "Pet Friendly"],
      tags: ["beach", "music", "nightlife"],
      rating: 4.8,
      reviewCount: 220,
      totalBookings: 36,
      totalRevenue: 4320000,
      status: "active" as const,
      isTopPick: true,
      isFeatured: true,
    },
    {
      organizerEmail: "fatima@goavibes.in",
      name: "Sunset Palm Deck",
      description: "A cozy deck venue for buffet nights, micro weddings, and tropical social evenings.",
      city: "Goa",
      address: "Candolim, Goa",
      coordinates: [73.7587, 15.5183],
      coverImage: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=2070&auto=format&fit=crop",
      images: [
        "https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=2070&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1484154218962-a197022b5858?q=80&w=2070&auto=format&fit=crop",
      ],
      capacity: 120,
      pricePerEvent: 70000,
      eventTypes: ["Buffet Night", "Private Party", "Engagement"],
      amenities: ["Bar", "Parking", "Stage"],
      tags: ["sunset", "deck", "buffet"],
      rating: 4.5,
      reviewCount: 64,
      totalBookings: 18,
      totalRevenue: 1260000,
      status: "active" as const,
    },
    {
      organizerEmail: "vikram@royaludaipur.com",
      name: "Heritage Palace Courtyard",
      description: "A breathtaking Udaipur palace courtyard for heritage weddings, royal dinners, and cultural shows.",
      city: "Udaipur",
      address: "Lake Pichola Road, Udaipur",
      coordinates: [73.6824, 24.5760],
      coverImage: "https://images.unsplash.com/photo-1590073844006-3a44a7f3df31?q=80&w=2070&auto=format&fit=crop",
      images: [
        "https://images.unsplash.com/photo-1590073844006-3a44a7f3df31?q=80&w=2070&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1587502536575-6dfba0a6e017?q=80&w=2070&auto=format&fit=crop",
      ],
      capacity: 1000,
      pricePerEvent: 420000,
      eventTypes: ["Destination Wedding", "Cultural Show", "Royal Reception"],
      amenities: ["Parking", "Catering", "Photography", "Valet", "Green Room"],
      tags: ["heritage", "royal", "destination"],
      rating: 5.0,
      reviewCount: 188,
      totalBookings: 22,
      totalRevenue: 9240000,
      status: "active" as const,
    },
  ];

  for (const item of venues) {
    const organizer = userByEmail.get(item.organizerEmail);
    if (!organizer) {
      continue;
    }
    const organizerProfile = profileByUserId.get(String(organizer._id));
    await Venue.create({
      organizer: organizer._id,
      organizerProfile: organizerProfile?._id,
      name: item.name,
      description: item.description,
      city: item.city,
      address: item.address,
      location: {
        type: "Point",
        coordinates: item.coordinates,
      },
      coverImage: item.coverImage,
      images: item.images,
      capacity: item.capacity,
      pricePerEvent: item.pricePerEvent,
      eventTypes: item.eventTypes,
      amenities: item.amenities,
      tags: item.tags,
      rating: item.rating,
      reviewCount: item.reviewCount,
      totalBookings: item.totalBookings,
      totalRevenue: item.totalRevenue,
      status: item.status,
      isTopPick: item.isTopPick ?? false,
      isFeatured: item.isFeatured ?? false,
      availability: {
        blockedDates: [],
        bookedDates: [],
      },
      policies: {
        minAdvanceBookingDays: 7,
        cancellationPolicy: "partial_refund",
        checkInTime: "10:00 AM",
        checkOutTime: "11:00 PM",
        securityDeposit: item.pricePerEvent > 200000 ? 50000 : 15000,
      },
    });
  }
};
